### PR TITLE
add trailing slash to scoped packages

### PR DESCRIPTION
**Pull request by SamVerschueren**
Wanted to do the tweaks and the fix into separate PR's but had to fix the implementation because of XO so I fixed everything into one PR. If you want separate PR's, let me know.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Just commit all the unrelated stuff directly to master and then rebase your PR ;)

**Comment by SamVerschueren** [comment]
Done! Have difficulties squashing them though.

**Comment by SamVerschueren** [comment]
Ping :)

**Comment by sindresorhus** [comment]
:+1:

**Comment by SamVerschueren** [comment]
Nice, thanks :)

**Pull request merged**
